[project]
name = "training"
version = "0.1.0"
description = "TermChess RL Training Pipeline"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "python-chess>=1.999",
    "torch>=2.10.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
